# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.3 on 2017-08-10 20:19
=======
# Generated by Django 1.11.3 on 2017-08-10 19:23
>>>>>>> 6a9604aee0aa22c4ea702613983a6f624b9c43ac
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
=======
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 8, 10, 19, 23, 39, 66522, tzinfo=utc))),
                ('approved_comment', models.BooleanField(default=False)),
>>>>>>> 6a9604aee0aa22c4ea702613983a6f624b9c43ac
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
<<<<<<< HEAD
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 8, 10, 20, 19, 1, 991929, tzinfo=utc))),
=======
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 8, 10, 19, 23, 39, 65868, tzinfo=utc))),
>>>>>>> 6a9604aee0aa22c4ea702613983a6f624b9c43ac
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
